# API documentation: https://developers.linode.com/api/v4/
linode_label: wiley
linode_type: g6-nanode-1 # https://api.linode.com/v4/linode/types
linode_region: us-east # https://api.linode.com/v4/regions
linode_image: linode/ubuntu19.10 # https://api.linode.com/v4/images
# create Personal Access Token by clicking your profile in the upper right
# My Profile -> API Tokens -> [+] Add a Personal Access Token
# Give read/write access to at least Linodes, if not everything else
# Put PAT in ansible hosts file e.g. /usr/local/etc/ansible/hosts
# under [local:vars] after defining [local] as localhost
linode_token: '{{ pvd_linode_token }}'
# password: "{{ pass_attenborough }}"

# put local_hostname in [inventory_directory]/host_vars/[servername]
inventory_directory: /etc/ansible
