default_pass: "$6$mysecretsalt$KX2mLFmN1x9gF/urPk7EpzaMJMcY4yoFetMlQw0W9Lm2MJZ8cVI/7dk25PVyb6cLx7IUwTxON5HucMHOdsP.Y0"
admin_email: skyfaller@gmail.com

users:
  - name: nelson
    password: "{{ default_pass }}"
    shell: /bin/bash
    sshKey: 
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDDMjjO5XKL+RqMIInA85ZVycw7D1OApFlUNCEQgTejQKqIWXHeXgweI+u/OcRlHIeBGmPCAKGmSnPrhDKSsjhYMWYrL1lLb1n3lVASsr4Ermp9FUoxys1QlKuKhuoggnXVRZMB2lzOD/LZkQ/iAhBhtLHnqLnVFE0XZ6tksR2rMO+FI3VpcqR/zXDoZQmWIX7wGm1JcQWPdJgtP1TYkBNRusPbFJdwH/xTM0BwGLVY0M9o9OCmkKZryNmcJl8ymv6DtCY122h8U8+QmR9bDFdWjwEc0mLHSnjhYMJdKBgbqwrVU24Dri9RMrqHEQTRk3FTgF6/WhkvsHHZuI8XUBwH nelson@Valence.local # noqa 204 - turn off Ansible linter
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHhOEJBnYlsQ/+6T3L0GxagZdCCCgqOaGFtgh5agZB4P u0_a278@localhost

handcoded_websites:
  - subdomain: www
    domain_name: sunrisepvd.com
    git_repo: https://github.com/sunriseprovidence/sunrisepvd.com.git